seed: 12450
epochs: 600
batch_size: 128
T: 4
model: spikingresformer_cifar
dataset: CIFAR100
augment: rand-m7-n1-mstd0.5-inc1
mixup: True
cutout: False
label_smoothing: 0.1
workers: 16
lr: 5e-4
optimizer: adamw
weight_decay: 0.01
input_size: [3, 32, 32]

TET: False
TET_phi: 1.0
TET_lambda: 0.0

save_latest: False
test_only: False
amp: True
sync_bn: False
