seed: 12450
epochs: 150
batch_size: 128
T: 4
model: spikingresformer_s
dataset: CIFAR100
augment: rand-m9-n1-mstd0.4-inc1
mixup: True
cutout: False
label_smoothing: 0.1
workers: 16
lr: 0.0001
optimizer: adamw
weight_decay: 0.01
input_size: [3, 128, 128]

TET: False
TET_phi: 1.0
TET_lambda: 0.0

save_latest: False
test_only: False
amp: True
sync_bn: False
