seed: 12450
epochs: 320
batch_size: 32
T: 4
model: spikingresformer_ti
dataset: ImageNet
augment: rand-m7-mstd0.5-inc1
mixup: True
cutout: False
label_smoothing: 0.1
workers: 16
lr: 0.001
optimizer: adamw
weight_decay: 0.01
input_size: [3, 224, 224]

TET: False
TET_phi: 1.0
TET_lambda: 0.0

save_latest: False
test_only: False
amp: True
sync_bn: False
